print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/newmac/Documents/vel/Tracking/Assets/Secretary/CivilianChicks/Maya Binary Files/rightfootnoskeleton.mb"`)
{		
	file -o "/Users/newmac/Documents/vel/Tracking/Assets/Secretary/CivilianChicks/Maya Binary Files/rightfootnoskeleton.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/newmac/Documents/vel/Tracking/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/newmac/Documents/vel/Tracking/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/newmac/Documents/vel/Tracking/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
